version: '3.9'

services:

  psql-app:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./psql-app/psql-files:/var/lib/postgresql/data
      - ./psql-app/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    container_name: velib_db
    ports:
      - "5432:5432"

  python-app:
    build : 
      context : ./python-app
      dockerfile : Dockerfile
    container_name: db_writer

