services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "velib_db"
    ports:
      - "5432:5432"
    volumes:
      - ./psql_app/psql_files:/var/lib/postgresl/data
      - ./psql_app/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  python:
    container_name: python_scraper
    tty: true
    environment:
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "velib_db"
    build:
      context: ./python_app
