services:
  db_app:
    image: postgres
    container_name: postgres_db
    user: postgres
    environment:
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "velib_db"
    ports:
      - "5432:5432"
    volumes:
      - ./psql_app/psql_files:/var/lib/postgresl/data
      - ./psql_app/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  scraper_app:
    container_name: scraper
    tty: true
    environment:
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "velib_db"
    build:
      context: ./python_apps
      dockerfile: scraper.Dockerfile

  front_app:
    container_name: front
    tty: true
    environment:
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "velib_db"
    ports:
      - "8050:8050"
    build:
      context: ./python_apps
      dockerfile: front.Dockerfile
